#!/bin/bash

# Minecraft Bedrock Server Manager v1.0 Clean Edition
# A complete CLI-based server management solution

# ============================================
# CONFIGURATION AND COLORS
# ============================================

# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Base directories
BASE_DIR="/home/minecraft"
SCRIPT_NAME=$(basename "$0")
VERSION="v1.0 Clean Edition"

# ============================================
# UTILITY FUNCTIONS
# ============================================

print_header() {
    clear
    echo -e "${CYAN}========================================${NC}"
    echo -e "${WHITE}   Minecraft Bedrock Manager ${VERSION}${NC}"
    echo -e "${CYAN}========================================${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_info() {
    echo -e "${CYAN}[INFO]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root"
        exit 1
    fi
}

# ============================================
# DEPENDENCY INSTALLATION
# ============================================

install_dependencies() {
    print_info "Checking and installing dependencies..."
    
    # Update package list
    apt-get update -qq
    
    # Install required packages
    DEPS=("unzip" "curl" "wget" "tmux" "openssh-server")
    
    for dep in "${DEPS[@]}"; do
        if ! command -v "$dep" &> /dev/null; then
            print_info "Installing $dep..."
            apt-get install -y "$dep" > /dev/null 2>&1
            print_success "$dep installed"
        else
            print_success "$dep already installed"
        fi
    done
    
    # Ensure tmux is available
    if ! command -v tmux &> /dev/null; then
        print_error "tmux installation failed"
        exit 1
    fi
    
    print_success "All dependencies installed"
}

# ============================================
# SERVER PROPERTIES GENERATOR
# ============================================

generate_server_properties() {
    local server_name="$1"
    local gamemode="$2"
    local difficulty="$3"
    local allow_cheats="$4"
    local server_port="$5"
    local level_name="$6"
    local level_seed="$7"
    local server_dir="$8"
    
    cat > "$server_dir/server.properties" << EOF
# Minecraft Bedrock Server Properties
# Generated by Minecraft Bedrock Manager v1.0

server-name=$server_name
gamemode=$gamemode
force-gamemode=false
difficulty=$difficulty
allow-cheats=$allow_cheats
max-players=99999
online-mode=true
allow-list=false
server-port=$server_port
server-portv6=$((server_port+1))
enable-lan-visibility=true
view-distance=10
tick-distance=4
player-idle-timeout=120
max-threads=8
level-name=$level_name
level-seed=$level_seed
default-player-permission-level=member
texturepack-required=false
content-log-file-enabled=false
compression-threshold=1
compression-algorithm=zlib

# Advanced movement settings
server-authoritative-movement-strict=false
server-authoritative-dismount-strict=false
server-authoritative-entity-interactions-strict=false
player-position-acceptance-threshold=0.5
player-movement-action-direction-threshold=0.85
server-authoritative-block-breaking-pick-range-scalar=1.5

# Client-side settings
chat-restriction=None
disable-player-interaction=false
client-side-chunk-generation-enabled=true
block-network-ids-are-hashes=true
disable-persona=false
disable-custom-skins=false

# Debug and development settings
server-build-radius-ratio=Disabled
allow-outbound-script-debugging=false
allow-inbound-script-debugging=false
script-debugger-auto-attach=disabled

# Query and discovery
enable-query=true
EOF

    print_success "server.properties generated with custom settings"
    
    # Explanation of key settings
    echo ""
    print_info "Server Properties Explanation:"
    echo "  - server-portv6 = port+1 (IPv6 uses next port)"
    echo "  - max-players=99999 (Removes player limit for large communities)"
    echo "  - view-distance=10 (Balances performance vs visibility)"
    echo "  - tick-distance=4 (Optimizes chunk loading)"
    echo "  - max-threads=8 (Optimized for multi-core CPUs)"
}

# ============================================
# CHECK AVAILABLE SLOTS
# ============================================

get_available_slots() {
    local used_slots=()
    
    # Check existing users
    for i in {1..10}; do
        if id "mcserver$i" &>/dev/null; then
            used_slots+=($i)
        fi
    done
    
    # Find first available slot
    for i in {1..10}; do
        if [[ ! " ${used_slots[@]} " =~ " $i " ]]; then
            echo "$i"
            return 0
        fi
    done
    
    echo "0" # No available slots
    return 1
}

# ============================================
# GET LATEST BEDROCK VERSION
# ============================================

get_latest_version() {
    local version_url="https://www.minecraft.net/en-us/download/server/bedrock"
    local download_page=$(curl -s "$version_url")
    local version=$(echo "$download_page" | grep -oP 'bedrock-server-\K[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -1)
    
    if [[ -z "$version" ]]; then
        echo "1.20.80.05" # Fallback version
    else
        echo "$version"
    fi
}

# ============================================
# GENERATE RANDOM PASSWORD
# ============================================

generate_password() {
    openssl rand -base64 12 | tr -d "=+/" | cut -c1-16
}

# ============================================
# CREATE SYSTEMD SERVICE
# ============================================

create_systemd_service() {
    local server_num="$1"
    local server_user="mcserver$server_num"
    local server_dir="$BASE_DIR/mcserver$server_num"
    
    cat > "/etc/systemd/system/mcserver$server_num.service" << EOF
[Unit]
Description=Minecraft Bedrock Server $server_num
After=network.target

[Service]
Type=forking
User=$server_user
Group=$server_user
WorkingDirectory=$server_dir
ExecStart=/usr/bin/tmux new-session -d -s mcserver$server_num -c $server_dir './bedrock_server'
ExecStop=/usr/bin/tmux send-keys -t mcserver$server_num "stop" C-m
ExecReload=/usr/bin/tmux send-keys -t mcserver$server_num "reload" C-m
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    print_success "Systemd service created for mcserver$server_num"
}

# ============================================
# INSTALL SERVER FUNCTION
# ============================================

install_server() {
    print_header
    echo -e "${WHITE}Server Installation Wizard${NC}"
    echo ""
    
    # Check available slots
    local slot=$(get_available_slots)
    if [[ "$slot" -eq "0" ]]; then
        print_error "No available server slots (max 10 servers)"
        return 1
    fi
    
    # Get number of servers to install
    read -p "Number of servers to install (1-10, default: 1): " num_servers
    num_servers=${num_servers:-1}
    
    if [[ ! "$num_servers" =~ ^[1-9]|10$ ]]; then
        print_error "Invalid number. Using default: 1"
        num_servers=1
    fi
    
    # Check if we have enough slots
    local available_slots=0
    for i in {1..10}; do
        if ! id "mcserver$i" &>/dev/null; then
            ((available_slots++))
        fi
    done
    
    if [[ "$num_servers" -gt "$available_slots" ]]; then
        print_error "Only $available_slots slots available. Requested: $num_servers"
        return 1
    fi
    
    # Get version
    local latest_version=$(get_latest_version)
    read -p "Server version (default: $latest_version): " version
    version=${version:-$latest_version}
    
    # Create base directory if it doesn't exist
    mkdir -p "$BASE_DIR"
    
    # Install each server
    local installed=0
    for i in {1..10}; do
        if [[ "$installed" -ge "$num_servers" ]]; then
            break
        fi
        
        if ! id "mcserver$i" &>/dev/null; then
            print_header
            echo -e "${WHITE}Installing Server #$i${NC}"
            echo ""
            
            # Server configuration
            local server_name
            read -p "Server name (default: server$i): " server_name
            server_name=${server_name:-server$i}
            
            local server_port=$((19132 + (i-1) * 2))
            read -p "Server port (default: $server_port): " input_port
            server_port=${input_port:-$server_port}
            
            local gamemode
            read -p "Gamemode (survival/creative/adventure, default: survival): " gamemode
            gamemode=${gamemode:-survival}
            
            local difficulty
            read -p "Difficulty (peaceful/easy/normal/hard, default: normal): " difficulty
            difficulty=${difficulty:-normal}
            
            local allow_cheats
            read -p "Allow cheats (true/false, default: false): " allow_cheats
            allow_cheats=${allow_cheats:-false}
            
            local level_name
            read -p "Level name (default: Bedrock level): " level_name
            level_name=${level_name:-"Bedrock level"}
            
            local level_seed
            read -p "Level seed (leave empty for random): " level_seed
            
            echo ""
            print_info "Creating server user and directory..."
            
            # Create user
            local password=$(generate_password)
            useradd -m -d "$BASE_DIR/mcserver$i" -s /bin/bash -U "mcserver$i"
            echo "mcserver$i:$password" | chpasswd
            
            # Set permissions
            chown -R "mcserver$i:mcserver$i" "$BASE_DIR/mcserver$i"
            chmod 755 "$BASE_DIR/mcserver$i"
            
            # Download server files
            print_info "Downloading Minecraft Bedrock Server v$version..."
            local download_url="https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-$version.zip"
            
            if ! wget -q "$download_url" -O "/tmp/bedrock-server-$version.zip"; then
                print_error "Failed to download server files"
                userdel -r "mcserver$i"
                return 1
            fi
            
            # Extract files
            print_info "Extracting server files..."
            unzip -q "/tmp/bedrock-server-$version.zip" -d "$BASE_DIR/mcserver$i/"
            
            # Generate server.properties
            generate_server_properties "$server_name" "$gamemode" "$difficulty" "$allow_cheats" "$server_port" "$level_name" "$level_seed" "$BASE_DIR/mcserver$i"
            
            # Set proper ownership
            chown -R "mcserver$i:mcserver$i" "$BASE_DIR/mcserver$i"
            chmod +x "$BASE_DIR/mcserver$i/bedrock_server"
            
            # Create systemd service
            create_systemd_service "$i"
            
            # Start server
            systemctl start "mcserver$i"
            systemctl enable "mcserver$i" > /dev/null 2>&1
            
            # Cleanup
            rm -f "/tmp/bedrock-server-$version.zip"
            
            # Display server info
            echo ""
            print_success "Server mcserver$i installed successfully!"
            echo ""
            echo -e "${WHITE}Server Information:${NC}"
            echo "  Username: mcserver$i"
            echo "  Password: $password"
            echo "  Server Path: $BASE_DIR/mcserver$i"
            echo "  Port: $server_port"
            echo ""
            echo -e "${WHITE}Control Commands:${NC}"
            echo "  Start:   systemctl start mcserver$i"
            echo "  Stop:    systemctl stop mcserver$i"
            echo "  Restart: systemctl restart mcserver$i"
            echo "  Status:  systemctl status mcserver$i"
            echo ""
            echo -e "${WHITE}Console Commands:${NC}"
            echo "  Send command: tmux send-keys -t mcserver$i \"say Hello\" C-m"
            echo "  Attach console: tmux attach -t mcserver$i"
            echo "  (Press Ctrl+B, then D to detach)"
            echo ""
            echo -e "${CYAN}----------------------------------------${NC}"
            
            ((installed++))
        fi
    done
    
    print_success "Installation complete! $installed server(s) installed."
}

# ============================================
# UNINSTALL SERVER
# ============================================

uninstall_server() {
    print_header
    echo -e "${WHITE}Uninstall Server${NC}"
    echo ""
    
    # List installed servers
    local servers=()
    for i in {1..10}; do
        if id "mcserver$i" &>/dev/null; then
            servers+=($i)
        fi
    done
    
    if [[ ${#servers[@]} -eq 0 ]]; then
        print_error "No servers installed"
        return 1
    fi
    
    echo "Installed servers:"
    for i in "${servers[@]}"; do
        echo "  $i. mcserver$i"
    done
    echo ""
    
    read -p "Enter server number to uninstall: " server_num
    
    if [[ ! " ${servers[@]} " =~ " ${server_num} " ]]; then
        print_error "Invalid server number"
        return 1
    fi
    
    print_warning "This will permanently delete server mcserver$server_num"
    read -p "Are you sure? (y/N): " confirm
    
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        print_info "Stopping and disabling service..."
        systemctl stop "mcserver$server_num"
        systemctl disable "mcserver$server_num" > /dev/null 2>&1
        rm -f "/etc/systemd/system/mcserver$server_num.service"
        systemctl daemon-reload
        
        print_info "Removing user and files..."
        userdel -r "mcserver$server_num" 2>/dev/null
        
        print_success "Server mcserver$server_num uninstalled"
    else
        print_info "Uninstall cancelled"
    fi
}

# ============================================
# SERVER CONTROL FUNCTIONS
# ============================================

control_server() {
    local action="$1"
    local action_past="$2"
    
    print_header
    echo -e "${WHITE}${action} Server${NC}"
    echo ""
    
    # List running servers
    local servers=()
    for i in {1..10}; do
        if id "mcserver$i" &>/dev/null; then
            servers+=($i)
        fi
    done
    
    if [[ ${#servers[@]} -eq 0 ]]; then
        print_error "No servers installed"
        return 1
    fi
    
    echo "Available servers:"
    for i in "${servers[@]}"; do
        local status=$(systemctl is-active "mcserver$i" 2>/dev/null)
        local status_color
        if [[ "$status" == "active" ]]; then
            status_color="${GREEN}● Running${NC}"
        else
            status_color="${RED}○ Stopped${NC}"
        fi
        echo "  $i. mcserver$i - $status_color"
    done
    echo ""
    
    read -p "Enter server number to $action: " server_num
    
    if [[ ! " ${servers[@]} " =~ " ${server_num} " ]]; then
        print_error "Invalid server number"
        return 1
    fi
    
    systemctl "$action" "mcserver$server_num"
    
    if [[ $? -eq 0 ]]; then
        print_success "Server mcserver$server_num ${action_past}"
    else
        print_error "Failed to ${action} server mcserver$server_num"
    fi
}

# ============================================
# LIST SERVERS
# ============================================

list_servers() {
    print_header
    echo -e "${WHITE}Server List${NC}"
    echo ""
    
    local any_server=false
    
    for i in {1..10}; do
        if id "mcserver$i" &>/dev/null; then
            any_server=true
            local status=$(systemctl is-active "mcserver$i" 2>/dev/null)
            local port=$(grep -Po '(?<=server-port=).*' "$BASE_DIR/mcserver$i/server.properties" 2>/dev/null)
            local players="0"
            
            # Try to get player count from tmux session
            if [[ "$status" == "active" ]]; then
                local player_output=$(tmux capture-pane -t "mcserver$i" -p 2>/dev/null | grep -oP '\d+/\d+ players' | tail -1)
                if [[ -n "$player_output" ]]; then
                    players="$player_output"
                fi
            fi
            
            echo -e "${CYAN}Server mcserver$i${NC}"
            echo "  Status: $(if [[ "$status" == "active" ]]; then echo -e "${GREEN}Running${NC}"; else echo -e "${RED}Stopped${NC}"; fi)"
            echo "  Port: $port"
            echo "  Players: $players"
            echo "  Path: $BASE_DIR/mcserver$i"
            echo ""
        fi
    done
    
    if [[ "$any_server" == false ]]; then
        print_warning "No servers installed"
    fi
    
    read -p "Press Enter to continue..."
}

# ============================================
# REAL-TIME MONITOR
# ============================================

real_time_monitor() {
    print_header
    echo -e "${WHITE}Real-time Server Monitor (Press Ctrl+C to exit)${NC}"
    echo ""
    
    while true; do
        clear
        echo -e "${CYAN}========================================${NC}"
        echo -e "${WHITE}   Server Monitor - $(date '+%H:%M:%S')${NC}"
        echo -e "${CYAN}========================================${NC}"
        echo ""
        
        printf "%-12s %-10s %-8s %-8s %-10s %s\n" "SERVER" "STATUS" "CPU%" "RAM(MB)" "PLAYERS" "PORT"
        echo "--------------------------------------------------------------------------------"
        
        for i in {1..10}; do
            if id "mcserver$i" &>/dev/null; then
                local status=$(systemctl is-active "mcserver$i" 2>/dev/null)
                local port=$(grep -Po '(?<=server-port=).*' "$BASE_DIR/mcserver$i/server.properties" 2>/dev/null)
                local cpu=0
                local mem=0
                local players="0/?"
                
                if [[ "$status" == "active" ]]; then
                    # Get CPU and memory usage
                    local pid=$(pgrep -f "tmux.*mcserver$i.*bedrock_server")
                    if [[ -n "$pid" ]]; then
                        cpu=$(ps -p $pid -o %cpu --no-headers 2>/dev/null | cut -d. -f1)
                        mem=$(ps -p $pid -o rss --no-headers 2>/dev/null | awk '{printf "%.0f", $1/1024}')
                        cpu=${cpu:-0}
                        mem=${mem:-0}
                    fi
                    
                    # Get player count from logs
                    local player_count=$(tmux capture-pane -t "mcserver$i" -p 2>/dev/null | grep -oP '\d+/\d+ players' | tail -1)
                    players=${player_count:-"0/?"}
                    
                    echo -e "mcserver$i    ${GREEN}● Running${NC}   $cpu     $mem      $players    $port"
                else
                    echo -e "mcserver$i    ${RED}○ Stopped${NC}   -       -        -         $port"
                fi
            fi
        done
        
        echo ""
        echo -e "${YELLOW}System Resources:${NC}"
        echo "  CPU Usage: $(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d. -f1)%"
        echo "  RAM Usage: $(free -m | awk 'NR==2{printf "%.1f/%.1f MB (%.1f%%)", $3, $2, $3*100/$2}')"
        echo "  Disk Usage: $(df -h / | awk 'NR==2{print $5 " of " $2}')"
        
        sleep 5
    done
}

# ============================================
# ENTER SERVER CONSOLE
# ============================================

enter_server_console() {
    print_header
    echo -e "${WHITE}Server Console${NC}"
    echo ""
    
    # List running servers
    local servers=()
    for i in {1..10}; do
        if id "mcserver$i" &>/dev/null; then
            local status=$(systemctl is-active "mcserver$i" 2>/dev/null)
            if [[ "$status" == "active" ]]; then
                servers+=($i)
            fi
        fi
    done
    
    if [[ ${#servers[@]} -eq 0 ]]; then
        print_error "No running servers found"
        read -p "Press Enter to continue..."
        return 1
    fi
    
    echo "Running servers:"
    for i in "${servers[@]}"; do
        echo "  $i. mcserver$i"
    done
    echo ""
    
    read -p "Select server number: " server_num
    
    if [[ ! " ${servers[@]} " =~ " ${server_num} " ]]; then
        print_error "Invalid server number"
        read -p "Press Enter to continue..."
        return 1
    fi
    
    echo ""
    echo -e "${YELLOW}Console Options:${NC}"
    echo "  1. Attach to tmux (full console)"
    echo "  2. Command mode (send individual commands)"
    read -p "Select option (1-2): " console_mode
    
    case $console_mode in
        1)
            print_info "Attaching to mcserver$server_num console..."
            print_info "Press Ctrl+B then D to detach"
            sleep 2
            tmux attach -t "mcserver$server_num"
            ;;
        2)
            echo ""
            echo -e "${CYAN}Entering command mode for mcserver$server_num${NC}"
            echo -e "${YELLOW}Type 'exit' to return to menu${NC}"
            echo -e "${YELLOW}Type 'help' for command list${NC}"
            echo ""
            
            while true; do
                read -p "[mcserver$server_num CMD] > " cmd
                
                if [[ "$cmd" == "exit" ]]; then
                    break
                elif [[ "$cmd" == "help" ]]; then
                    echo "Available commands:"
                    echo "  say <message>  - Broadcast message"
                    echo "  list           - List players"
                    echo "  stop           - Stop server"
                    echo "  reload         - Reload server"
                    echo "  save           - Save world"
                    echo "  help           - Show this help"
                    echo "  exit           - Exit console mode"
                elif [[ -n "$cmd" ]]; then
                    tmux send-keys -t "mcserver$server_num" "$cmd" C-m
                    print_success "Command sent"
                    
                    # Show last line of output
                    sleep 0.5
                    tmux capture-pane -t "mcserver$server_num" -p | tail -3
                    echo ""
                fi
            done
            ;;
        *)
            print_error "Invalid option"
            ;;
    esac
}

# ============================================
# MAIN MENU
# ============================================

main_menu() {
    while true; do
        print_header
        
        echo -e "${WHITE}Main Menu${NC}"
        echo ""
        echo "  1. Install Server"
        echo "  2. Uninstall Server"
        echo "  3. Start Server"
        echo "  4. Stop Server"
        echo "  5. Restart Server"
        echo "  6. List Servers"
        echo "  7. Real-time Monitor"
        echo "  8. Enter Server Console"
        echo "  9. Exit"
        echo ""
        
        read -p "Select option (1-9): " choice
        
        case $choice in
            1) install_server ;;
            2) uninstall_server ;;
            3) control_server "start" "started" ;;
            4) control_server "stop" "stopped" ;;
            5) control_server "restart" "restarted" ;;
            6) list_servers ;;
            7) real_time_monitor ;;
            8) enter_server_console ;;
            9) 
                print_success "Goodbye!"
                exit 0 
                ;;
            *)
                print_error "Invalid option"
                sleep 2
                ;;
        esac
    done
}

# ============================================
# SCRIPT INITIALIZATION
# ============================================

# Check if running as root
check_root

# Install dependencies
install_dependencies

# Create base directory if it doesn't exist
mkdir -p "$BASE_DIR"

# Start main menu
main_menu
